### ISSUE TITLE
unable to detect libmodbus on debian10

### ISSUE THREAD

**Issue by VeganBiker** [danieloneill/EpsolarServer#11]
I'm attempting to set this up however when I run qmake i get the following:

oem@emoncms:~/EpsolarServer$ qmake
Project ERROR: libmodbus development package not found

libmodbus-dev is installed however.

oem@emoncms:~/EpsolarServer$ apt list libmodbus*
Listing... Done
libmodbus-dev/stable,now 3.1.4-2 amd64 [installed]
libmodbus5/stable,now 3.1.4-2 amd64 [installed]

**Comment by danieloneill** [comment]
Install libmodbus

**Comment by VeganBiker** [comment]
I don't have a package named libmodbus to install, just libmodbus5

**Comment by VeganBiker** [comment]
I do have it working via socat and a virtual tty. Also Id like to use your code to try and setup a link to emoncms/emonhub with the tracer. I modified the webpage a little to make it more useful to my specific tracer as I have a Tracer AN without a load output.

**Comment by VeganBiker** [comment]
Needed to install pkg-config

apt install pkg-config

**Comment by hanthecat** [comment]
I ran into this as well. Debian Bullseye on a pi 0.
